sudo: false
language: python
python:
  - "3.5"
  # - "pypy3"
install:
  - pip install pytest pytest-cov pytest-pep8 codecov
script:
  - PYTHONPATH=. pytest --pep8 --cov-report term-missing --cov=mitest tests/
after_success:
  - codecov --token=$CODECOV_TOKEN
cache: pip
